// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: chat.proto

package pb_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OpenAIService_StreamChat_FullMethodName = "/chat.OpenAIService/StreamChat"
)

// OpenAIServiceClient is the client API for OpenAIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenAIServiceClient interface {
	StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (OpenAIService_StreamChatClient, error)
}

type openAIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenAIServiceClient(cc grpc.ClientConnInterface) OpenAIServiceClient {
	return &openAIServiceClient{cc}
}

func (c *openAIServiceClient) StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (OpenAIService_StreamChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &OpenAIService_ServiceDesc.Streams[0], OpenAIService_StreamChat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &openAIServiceStreamChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OpenAIService_StreamChatClient interface {
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type openAIServiceStreamChatClient struct {
	grpc.ClientStream
}

func (x *openAIServiceStreamChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OpenAIServiceServer is the server API for OpenAIService service.
// All implementations must embed UnimplementedOpenAIServiceServer
// for forward compatibility
type OpenAIServiceServer interface {
	StreamChat(*ChatRequest, OpenAIService_StreamChatServer) error
	mustEmbedUnimplementedOpenAIServiceServer()
}

// UnimplementedOpenAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOpenAIServiceServer struct {
}

func (UnimplementedOpenAIServiceServer) StreamChat(*ChatRequest, OpenAIService_StreamChatServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedOpenAIServiceServer) mustEmbedUnimplementedOpenAIServiceServer() {}

// UnsafeOpenAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenAIServiceServer will
// result in compilation errors.
type UnsafeOpenAIServiceServer interface {
	mustEmbedUnimplementedOpenAIServiceServer()
}

func RegisterOpenAIServiceServer(s grpc.ServiceRegistrar, srv OpenAIServiceServer) {
	s.RegisterService(&OpenAIService_ServiceDesc, srv)
}

func _OpenAIService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OpenAIServiceServer).StreamChat(m, &openAIServiceStreamChatServer{stream})
}

type OpenAIService_StreamChatServer interface {
	Send(*ChatResponse) error
	grpc.ServerStream
}

type openAIServiceStreamChatServer struct {
	grpc.ServerStream
}

func (x *openAIServiceStreamChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

// OpenAIService_ServiceDesc is the grpc.ServiceDesc for OpenAIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenAIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.OpenAIService",
	HandlerType: (*OpenAIServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _OpenAIService_StreamChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
